### ISSUE TITLE
Install of tmc failing on python 3.11.2

### ISSUE THREAD

**Issue by HoffmannTom** [testmycode/tmc-python-tester#8]
Hello,
when I try to install tmc on current python 3.11.2 I get the following dependency issues:
```
Defaulting to user installation because normal site-packages is not writeable
Collecting tmc
  Using cached tmc-1.0.2.tar.gz (20 kB)
  Preparing metadata (setup.py) ... done
Collecting requests==2.7.0
  Using cached requests-2.7.0-py2.py3-none-any.whl (470 kB)
Collecting argh==0.26.1
  Using cached argh-0.26.1.tar.gz (32 kB)
  Preparing metadata (setup.py) ... done
Collecting peewee==2.6.3
  Using cached peewee-2.6.3.tar.gz (1.7 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
      ImportError: cannot import name 'Callable' from 'collections' (C:\Program Files\Python3\Lib\collections\__init__.py)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Maybe some old dependencies prevent installation (?)

**Comment by Heliozoa** [comment]
Hi,
Sorry for the very late response, this repository isn't maintained very actively right now. There should be no need to install the package locally, as it should be included with every Python TMC exercise. If you do want to install it locally for some reason, try doing so directly from this repository; it looks like you may be trying to install from PyPI (with `pip install tmc` or the like), and the version that exists there is very old.

**Comment by HoffmannTom** [comment]
Hello!
Thanks for the feedback!
Perhaps you can use this ticket as a trigger to update the PIP package(?)
I think this one needs an update: https://pypi.org/project/tmc/ 
It shows a version from 2016
